[build]
  base = "."
  command = "npm ci --legacy-peer-deps && npm run build:core && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.19.5"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_USE_NETLIFY_EDGE = "true"

[context.production]
  command = "npm ci --legacy-peer-deps && npm run build"

[context.deploy-preview]
  command = "npm ci --legacy-peer-deps && npm run build"

[context.branch-deploy]
  command = "npm ci --legacy-peer-deps && npm run build"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.anthropic.com;"

# Next.js runtime with API routes support
[functions]
  node_bundler = "esbuild"
  # Don't include unnecessary files to keep function size small
  included_files = []
  external_node_modules = ["@anthropic-ai/sdk"]

# API routes handled by Next.js adapter plugin
# Functions are automatically created from api/ directory

# Essential Netlify plugin for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"