// 🎯 MAGIC NUMBERS EXTERMINATION - Centralized constants
// Created to eliminate 50+ magic number warnings

// 🧠 CONFIDENCE THRESHOLDS
export const CONFIDENCE_THRESHOLDS = {
  HIGH: 0.9,
  GOOD: 0.8,
  MEDIUM: 0.7,
  LOW: 0.6,
  MINIMUM: 0.5,
  CRITICAL: 0.95,
} as const

// ⚡ PERFORMANCE & TIMING
export const PERFORMANCE = {
  ANIMATION_DELAY: 2000,
  DEBOUNCE_DELAY: 300,
  SCROLL_DELAY: 100,
  HOVER_DELAY: 200,
  TRANSITION_FAST: 150,
  TRANSITION_MEDIUM: 300,
  TRANSITION_SLOW: 500,
} as const

// 📏 UI DIMENSIONS
export const UI_DIMENSIONS = {
  INPUT_MIN_HEIGHT: 44,
  INPUT_MAX_HEIGHT: 128,
  SIDEBAR_WIDTH: 280,
  MOBILE_BREAKPOINT: 768,
  HEADER_HEIGHT: 64,
  FOOTER_HEIGHT: 48,
} as const

// 📊 SYSTEM LIMITS
export const SYSTEM_LIMITS = {
  MAX_LINES_PER_FUNCTION: 200,
  MAX_COMPLEXITY: 15,
  MAX_ITERATIONS: 5,
  MIN_COMPLETENESS: 70,
  HEALTH_THRESHOLD: 70,
  PERFORMANCE_THRESHOLD: 25,
} as const

// 🔢 CALCULATION FACTORS
export const CALCULATION_FACTORS = {
  FADE_OPACITY: 0.2,
  BLUR_INTENSITY: 0.1,
  SCALE_FACTOR: 0.95,
  BOUNCE_FACTOR: 0.02,
  DAMPING_FACTOR: 0.08,
  SPRING_TENSION: 0.92,
  FRICTION_FACTOR: 0.05,
  VELOCITY_DECAY: 7.5,
  MOMENTUM_FACTOR: 12,
  SYSTEM_LOAD_FACTOR: 40,
} as const

// 🏥 MEDICAL SPECIFIC
export const MEDICAL_CONSTANTS = {
  NOM_COMPLIANCE_MIN: 80,
  DIAGNOSTIC_CONFIDENCE_MIN: 0.85,
  EXTRACTION_COMPLETENESS_MIN: 80,
  SYMPTOM_INTENSITY_MAX: 10,
  AGE_MIN: 0,
  AGE_MAX: 150,
  DEFAULT_CONTEXT_CONFIDENCE: 0.3,
  MIN_SYMPTOMS_CONFIDENCE: 0.0,
  TIMEOUT_DELAY: 800,
  INJECTION_DELAY: 100,
} as const

// 🎨 VISUAL THRESHOLDS
export const VISUAL_CONSTANTS = {
  KEYBOARD_THRESHOLD: 100,
  SESSION_DURATION_MULTIPLIER: 1000,
  PERCENTAGE_MULTIPLIER: 100,
  COMPLETENESS_HIGH: 90,
  COMPLETENESS_MEDIUM: 60,
} as const

export type ConfidenceLevel = keyof typeof CONFIDENCE_THRESHOLDS
export type PerformanceMetric = keyof typeof PERFORMANCE
export type UIDimension = keyof typeof UI_DIMENSIONS
export type SystemLimit = keyof typeof SYSTEM_LIMITS
